/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        int x = 5;

        if ( x = 10 ) {
            System.out.printf("Hello");
        } else {
            System.out.printf("No");
        }
    }
}
